# Build pdf file in gh actions 
name: MyST PDF builder

on:
  push:
    branches: [main]
env:
  BASE_URL: /${{ github.event.repository.name }}

permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: 'pages'
  cancel-in-progress: false
jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex:latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install mystmd
        run: pip install mystmd

      - name: Install LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            texlive-latex-extra \
            texlive-fonts-recommended \
            texlive-fonts-extra \
            texlive-latex-recommended \
            texlive-science \
            texlive-xetex \
            latexmk

      - name: Build PDFs
        run: myst build --pdf

      - name: Commit and push exports folder
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          ls -R exports || echo "exports folder missing"
          git add -A exports
          timestamp=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
          git commit -m "Update exports folder (${timestamp}) [skip ci]" || echo "No changes to commit"
          git push origin main
