name: MyST PDF builder

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - uses: actions/checkout@v3

      # 2️⃣ Install minimal dependencies
      - name: Install LaTeX + Python packages
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            texlive-latex-base \
            texlive-latex-recommended \
            texlive-fonts-recommended \
            texlive-xetex \
            latexmk \
            nodejs \
            npm
          python -m pip install --upgrade pip
          pip install mystmd

      # 3️⃣ Build PDFs
      - name: Build PDFs
        run: myst build --pdf

      # 4️⃣ Commit and push exports folder if changed
      - name: Commit and push exports folder
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Add exports folder
          git add -A exports

          # Commit if there are changes
          if ! git diff --cached --quiet; then
            timestamp=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
            git commit -m "Update exports folder (${timestamp}) [skip ci]"
            
            # Push using the built-in GITHUB_TOKEN
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
          else
            echo "No changes to commit"
          fi