# Build pdf file in gh actions 
name: MyST PDF builder

on:
  push:
    branches: [main]
env:
  BASE_URL: /${{ github.event.repository.name }}

permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: 'pages'
  cancel-in-progress: false
jobs:
  build:
    runs-on: ubuntu-latest
    container: luukfroling/myst-latex:latest  # <-- your pushed image

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Build PDFs
        run: myst build --pdf

      # Commit and push exports folder
      - name: Commit and push exports folder
        run: |
        
          # Check exports folder
          ls -R exports || echo "exports folder missing"

          # Configure git
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Commit only if there are changes
          git add -A exports
          if ! git diff --cached --quiet; then
            timestamp=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
            git commit -m "Update exports folder (${timestamp}) [skip ci]"
            git push origin main
          else
            echo "No changes to commit"
          fi
