# Build pdf file in gh actions 
name: MyST PDF builder

on:
  push:
    branches: [main]
env:
  BASE_URL: /${{ github.event.repository.name }}

permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: 'pages'
  cancel-in-progress: false
jobs:
  build:
    runs-on: ubuntu-latest
    container: engineervix/python-latex:3.12-slim-bookworm

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          
      - name: Install Git
        run: apt-get update && apt-get install -y git
      
      - uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Install mystmd
        run: pip install mystmd

      - name: Build PDFs
        run: myst build --pdf

      - name: Commit and push exports folder
        working-directory: /github/workspace
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          ls -R exports || echo "exports folder missing"
          git add -A exports
          timestamp=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
          git commit -m "Update exports folder (${timestamp}) [skip ci]" || echo "No changes to commit"
          git push origin main

