name: MyST PDF Builder [LaTeX Minimal]

on:
  workflow_dispatch:

permissions:
  contents: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - uses: actions/checkout@v3

      # Install Node
      - uses: actions/setup-node@v4
        with:
          node-version: 18.x

      # Install MyST CLI (Node wrapper)
      - name: Install MyST Markdown
        run: npm install -g mystmd

      # Install Python and pip (required by MyST CLI for LaTeX PDF)
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # Install LaTeX system packages
      - name: Install LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            texlive-latex-base \
            texlive-latex-recommended \
            texlive-fonts-recommended \
            texlive-xetex \
            latexmk

      # Build PDFs with error capture
      - name: Build PDFs
        id: build_pdfs
        run: |
          set -o pipefail
          myst build --pdf 2> >(tee build_errors.log >&2) || true
          if [ -s build_errors.log ]; then
            echo "### Errors during PDF build:" >> $GITHUB_STEP_SUMMARY
            cat build_errors.log >> $GITHUB_STEP_SUMMARY
            exit 1
          fi

      # Commit exports only if build succeeded
      - name: Commit and push exports
        if: success()
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add -A exports

          if ! git diff --cached --quiet; then
            timestamp=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
            git commit -m "Update exports folder [LaTeX] (${timestamp})"
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
          else
            echo "No changes to commit"