name: MyST PDF Builder [Typst]

on:
  workflow_dispatch:

permissions:
  contents: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - uses: actions/checkout@v3
      - uses: typst-community/setup-typst@v4
      # 2️⃣ Install Python + MyST
      # - name: Set up Python and install MyST
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y nodejs npm
      #     python -m pip install --upgrade pip
      #     pip install mystmd
      

      # 3️⃣ Install Typst (latest release via official install script)
      - name: Install Typst
        run: |
          typst --version

      # 4️⃣ Build PDFs with Typst
      - name: Build PDFs
        run: myst build --typst

      # 5️⃣ Commit and push exports folder
      - name: Commit and push exports
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add -A exports
          if ! git diff --cached --quiet; then
            timestamp=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
            git commit -m "Update exports folder (${timestamp})"
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
          else
            echo "No changes to commit"
          fi
